### ISSUE TITLE
export csv bug

### ISSUE THREAD

**Issue by gcollet** [atelierPartage/wasc#3]
il y a un pb quand on exporte en csv car il n'y a pas forcément un dictionnaire...
Faut que je fasse un truc plus malin qui va plus loin tant qu'il y a un dico.

**Comment by FrancoisLB** [comment]
Oui, j’avais vu ça. Le code que je t’avais envoyé commençait à faire une partie du job en bouclant sur les noms des entreprises. Mais  à ce niveau je récupérais encore un dico avec plusieurs clés… d’où mon appel à l’aid e ! 😊

 

De : Guillaume Collet ***@***.***> 
Envoyé : mardi 4 juillet 2023 01:20
À : atelierPartage/wasc ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [atelierPartage/wasc] export csv bug (Issue #3)

 

il y a un pb quand on exporte en csv car il n'y a pas forcément un dictionnaire...
Faut que je fasse un truc plus malin qui va plus loin tant qu'il y a un dico.

**Comment by gcollet** [comment]
J'ai résolu le problème en utilisant un dataframe pandas.
Pour chaque URL, les résultats des checkers sont stockés (dans l'ordre) dans une liste avec en en-tête le nom de l'organisation, l'url et le message d'erreur (si il y en a un).

Pour n sites à visiter, en résultat on a donc une liste contenant n listes. Chacune des sous-liste contenant les résultats d'un URL. J'espère que c'est clair.

Ensuite, j'utilise les fonction `to_csv` et `to_json` pour exporter en json (easy)

**Comment by FrancoisLB** [comment]
Hello, en voilà une bonne nouvelle ! Du coup est-ce que tu as republier une nouvelle version ? Dois-je faire un update ou c’est trop tôt ? Bravo et bonne soiréeEnvoyé de mon iPhone et rédigé par commande vocaleLe 5 juil. 2023 à 19:06, Guillaume Collet ***@***.***> a écrit :﻿
J'ai résolu le problème en utilisant un dataframe pandas.
Pour chaque URL, les résultats des checkers sont stockés (dans l'ordre) dans une liste avec en en-tête le nom de l'organisation, l'url et le message d'erreur (si il y en a un).
Pour n sites à visiter, en résultat on a donc une liste contenant n listes. Chacune des sous-lise contenant les résultats d'un URL. J'espère que c'est clair.
Ensuite, j'utilise les fonction to_csv et to_json pour exporter en json (easy)
